{% set name = "rb-inotify" %}
{% set version = "0.10.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 050062d4f31d307cca52c3f6a7f4b946df8de25fc4bd373e1a5142e41034a7ca

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-ffi >=1.0,<2

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'  # [linux]

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.md
  summary: A Ruby wrapper for Linux inotify, using FFI

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/guard/rb-inotify

extra:
  recipe-maintainers:
    - sodre
