travis:
  secure:
    BINSTAR_TOKEN: C13eowbfmmJOJvciVs/+gNIMly8476in5XYil5E9lUR5CBS6rBoKbygrQxNm1M/Frp8pHXXq0uxpvAaoY46cg7gvfSbSal19M8QzoABKiKbzq66xavlFZLx5LeKdUer0toukOg60Zd2hPW3NacqkbJxftyz6RFKTqgyPP8r30ZHM7u1BZPUOitjHaS78aPJkQ6iTwzgf022/Up8Ssi1ECGOSotGlYbs2+9DeC60BPJq8bkk8rMVQC6vQilNJYOr29f+e36yWMltVcFOawDFtiB3RfqSCSE6e/77QsmDkiqfJ5qgg+EfOcxAcDYwSW5owq7Or2jI4nhU5Q1KCFEIIQQxs2I9rC3YcFAmOr6ZJZDaIwF0QeJzS3d7A4jgbAQyov97Aajx5BNkcQ6CUjVap1/c+PGTD8kUocTcQbsOJx54xLP1j3TYB2fEABhw2YdkdtHBz25TI/7HPWhPQ8HXYJX3WTnM50ca0Rz/5UOOssyHfzEhYLsrWngw5tWRQxv7eLcv9FQzJSvXYtKB9YZo3AAShFub9lhhVURwpzRI1Xv4etHabqnn7IoAUahWiPgMZtt8HXffx+9DUiV5Qz8trzKDBI+NBw7itABdMGQ+LKvgSBnbeHlTZba892+SNwVGDBB5dJ1P8C09q8TZccIRZXv9ieyKSV1qpT1wX7WUL/Dk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
